# ----
# Site

title: L10n.ws
url: "https://l10nws.github.io/docs"
baseurl:
google_analytics_key: UA-72164927-1
show_full_navigation: true
google_site_verification: l0CTb-NMGRSdHY9BoKkeMQf9UdJfuXzYRtts6NZTQZg

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Localization and internationalization web service. It easy to manage translation, translate digital content and deliver it to your product.
keywords: l10n.ws,l10n,localization,i18n,internationalization,g11n,globalization,translation,locale,management,web service,platform,java,spring
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: L10n.ws
  links:
    - https://github.com/l10nws

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
